"""update item model with warehouse status

Revision ID: 6bf09ae4ea21
Revises: dcea02689220
Create Date: 2025-03-15 09:07:08.465996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf09ae4ea21'
down_revision = 'dcea02689220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_status', sa.Enum('received', 'not_received', 'on_delivery', name='warehouse_status'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('warehouse_status')

    # ### end Alembic commands ###
