"""update model for QC

Revision ID: ad8f6416c7c0
Revises: 8d4a842c60cd
Create Date: 2025-03-13 14:03:53.966487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8f6416c7c0'
down_revision = '8d4a842c60cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_lost', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_lost', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_column('date_lost')
        batch_op.drop_column('location_lost')

    # ### end Alembic commands ###
